move persistence_mutex variable to the file where it is used most
  GCC 10 default to -fno-common, which uncovers following errors:
/usr/bin/ld: from_client.o:/builddir/build/BUILD/owfs-3.2p3/module/owserver/src/c/../include/owserver.h:21:
multiple definition of `persistence_mutex';
owserver.o:/builddir/build/BUILD/owfs-3.2p3/module/owserver/src/c/../include/owserver.h:21: first defined here

  This can be fixed by moving variable definition from .h into .c file,
and using "extern" for other uses of the variable. For more info
see https://bugzilla.redhat.com/show_bug.cgi?id=1794368

Note: this commit partially reverts 34276f3412a3cdbe0f98142420ad271fab0ec5d3